packages:
  - packages/*
  - dev-packages/*
overrides:
  '@xmldom/xmldom@<0.8.12': '>=0.8.12'
patchedDependencies:
  fantasticon: patches/fantasticon.patch

preferWorkspacePackages: true

publicHoistPattern:
  - eslint
trustPolicy: no-downgrade
