packages:
  - packages/*
  - dev-packages/*
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@axonivy/*'
  - 'eslint-plugin-better-tailwindcss@4.4.0'
overrides:
  '@xmldom/xmldom@<0.8.12': '>=0.8.12'
patchedDependencies:
  fantasticon: patches/fantasticon.patch

preferWorkspacePackages: true

publicHoistPattern:
  - eslint
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # minutes (30 days)
