packages:
  - packages/*
  - dev-packages/*
allowBuilds:
  es5-ext: false
  esbuild: false
  ttf2woff2: false
minimumReleaseAgeExclude:
  - '@axonivy/*'
overrides:
  '@xmldom/xmldom@<0.8.12': '>=0.8.12'
patchedDependencies:
  fantasticon: patches/fantasticon.patch
preferWorkspacePackages: true
publicHoistPattern:
  - eslint
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # minutes (30 days)
verifyDepsBeforeRun: warn
registries:
  '@axonivy': 'https://npmjs-registry.ivyteam.ch/'
